[default]
# Default settings for all environments
DATABASE_NAME = ""
DATABASE_HOST = ""
DATABASE_PORT = ""
LOG_LEVEL = "info"

[development]
# Settings for the development environment
DATABASE_NAME = "us_dev_daas"
DATABASE_HOST = "localhost"
DATABASE_PORT = "5432"
LOG_LEVEL = "debug"

[integration]
# Settings for the development environment
DATABASE_NAME = "us_int_daas"
DATABASE_HOST = "localhost"
DATABASE_PORT = "5432"
LOG_LEVEL = "debug"

[production]
# Settings for the production environment
DATABASE_NAME = "us_prd_daas"
DATABASE_HOST = "localhost"
DATABASE_PORT = "5432"
LOG_LEVEL = "info"
