[default]
# Default settings for all environments
LOG_LEVEL = "info"
DATABASE_NAME = ""
DATABASE_HOST = ""
DATABASE_PORT = ""
SOLR_URL = ""
SOLR_COLLECTION_FACILITY = "facility"
SOLR_COLLECTION_ASSET = "asset"
DB_PROC_GET_ASSETS = "get_assets"
DB_PROC_GET_ASSET_ID = "get_assets_by_id"
DB_PROC_UPSERT_ASSET = "asset_upsert_from_json"
DB_PROC_CREATE_ASSET = "create_asset"
DB_PROC_UPDATE_ASSET = "update_asset"
DB_PROC_DELETE_ASSET = "delete_asset"

[development]
# Settings for the development environment
LOG_LEVEL = "debug"
DATABASE_NAME = "us_dev_daas"
DATABASE_HOST = "localhost"
DATABASE_PORT = "5432"
SOLR_URL = "http://localhost:8983/solr"
SOLR_COLLECTION_FACILITY = "facility"
SOLR_COLLECTION_ASSET = "asset"
DB_PROC_GET_ASSETS = "get_assets"
DB_PROC_GET_ASSET_ID = "get_assets_by_id"
DB_PROC_UPSERT_ASSET = "asset_upsert_from_json"
DB_PROC_CREATE_ASSET = "create_asset"
DB_PROC_UPDATE_ASSET = "update_asset"
DB_PROC_DELETE_ASSET = "delete_asset"

[integration]
# Settings for the development environment
LOG_LEVEL = "debug"
DATABASE_NAME = "us_int_daas"
DATABASE_HOST = "localhost"
DATABASE_PORT = "5432"
SOLR_URL = "http://localhost:8983/solr"
SOLR_COLLECTION_FACILITY = "facility"
SOLR_COLLECTION_ASSET = "asset"
DB_PROC_GET_ASSETS = "get_assets"
DB_PROC_GET_ASSET_ID = "get_assets_by_id"
DB_PROC_UPSERT_ASSET = "asset_upsert_from_json"
DB_PROC_CREATE_ASSET = "create_asset"
DB_PROC_UPDATE_ASSET = "update_asset"
DB_PROC_DELETE_ASSET = "delete_asset"

[production]
# Settings for the production environment
LOG_LEVEL = "info"
DATABASE_NAME = "us_prd_daas"
DATABASE_HOST = "localhost"
DATABASE_PORT = "5432"
SOLR_URL = "http://localhost:8983/solr"
SOLR_COLLECTION_FACILITY = "facility"
SOLR_COLLECTION_ASSET = "asset"
DB_PROC_GET_ASSETS = "get_assets"
DB_PROC_GET_ASSET_ID = "get_assets_by_id"
DB_PROC_UPSERT_ASSET = "asset_upsert_from_json"
DB_PROC_CREATE_ASSET = "create_asset"
DB_PROC_UPDATE_ASSET = "update_asset"
DB_PROC_DELETE_ASSET = "delete_asset"