[default]
# Default settings for all environments
LOG_LEVEL = "info"
SOLR_TIMEOUT = "10"
SOLR_MAX_ROW = 1000
SOLR_COLLECTION_ACCOUNT = "account"
SOLR_COLLECTION_FACILITY = "facility"
SOLR_COLLECTION_ASSET = "asset"
SOLR_COLLECTION_SERVICE = "service"
SOLR_COLLECTION_USER = "user"
SOLR_COLLECTION_USERFACILITY = "userfacility"
PAGINATION_SIZE_DB = "10"
PAGINATION_SIZE_SOLR = "10"

DOMAIN_NAME_ACCOUNT = "ACCOUNT"
DOMAIN_NAME_FACILITY = "FACILITY"
DOMAIN_NAME_ASSET = "ASSET"
DOMAIN_NAME_SERVICE = "SERVICE"
API_AUTH_FACILITY_KEY = "facility_nbr"
IDX_BUFFER_SIZE_ACCOUNT = "10"
IDX_BUFFER_SIZE_FACILITY = "10"
IDX_BUFFER_SIZE_ASSET = "10"
IDX_BUFFER_SIZE_SERVICE = "10"
IDX_BUFFER_SIZE_USER = "10"
IDX_BUFFER_SIZE_USERFACILITY = "10"
IDX_BUFFER_DURATION_ACCOUNT = "10"
IDX_BUFFER_DURATION_FACILITY = "10"
IDX_BUFFER_DURATION_ASSET = "10"
IDX_BUFFER_DURATION_SERVICE = "10"
IDX_BUFFER_DURATION_USER = "10"
IDX_BUFFER_DURATION_USERFACILITY = "10"
IDX_OVERRIDE_CONCURRENT_THREAD_COUNT = "5"
IDX_OVERRIDE_TIMESTEP_DAY_SIZE = "7"
IDX_EVENT_FETCH_KEY = "domain_nbr"
IDX_FETCH_KEY_ACCOUNT = "account_nbr"
IDX_FETCH_KEY_FACILITY = "facility_nbr"
IDX_FETCH_KEY_ASSET = "asset_nbr"
IDX_FETCH_KEY_SERVICE = "service_nbr"
IDX_FETCH_KEY_USER = "username"
IDX_FETCH_KEY_USERFACILITY = "id"

# DATABASE CONFIGURATIONS
DB_FUNC_LOG = "daas_log"
DB_FUNC_GET_USERFACILITY_BY_USER = "get_userfacility_by_user"
DB_FUNC_GET_EVENT_NOTIFICATION_BUFFER = "get_event_notification_buffer"
DB_FUNC_CLEAN_EVENT_NOTIFICATION_BUFFER = "clean_event_notification_buffer"
DB_FUNC_GET_INDEX_OVERRIDE = "get_index_override"
DB_FIELD_INDEX_OVERRIDE_SOURCE_TS = "index_source_ts"
DB_FIELD_INDEX_OVERRIDE_TARGET_TS = "index_target_ts"
DB_FUNC_CLEAN_INDEX_OVERRIDE = "clean_index_override"
DB_FUNC_GET_ACCOUNT = "get_account"
DB_FUNC_GET_FACILITY = "get_facility"
DB_FUNC_GET_ASSET = "get_asset"
DB_FUNC_GET_SERVICE= "get_service"
DB_FUNC_GET_USER = "get_user"
DB_FUNC_GET_USERFACILITY = "get_userfacility"
DB_FUNC_GET_BY_ID_ACCOUNT = "get_account_by_json"
DB_FUNC_GET_BY_ID_FACILITY = "get_facility_by_json"
DB_FUNC_GET_BY_ID_ASSET = "get_asset_by_json"
DB_FUNC_GET_BY_ID_SERVICE = "get_service_by_json"
DB_FUNC_GET_BY_ID_USER = "get_user_by_json"
DB_FUNC_GET_BY_ID_USERFACILITY = "get_userfacility_by_json"
DB_FUNC_UPSERT_ACCOUNT = "upsert_account_from_json"
DB_FUNC_UPSERT_FACILITY = "upsert_facility_from_json"
DB_FUNC_UPSERT_ASSET = "upsert_asset_from_json"
DB_FUNC_UPSERT_SERVICE = "upsert_service_from_json"
DB_FUNC_UPSERT_USER = "upsert_user_from_json"
DB_FUNC_UPSERT_USERFACILITY = "upsert_userfacility_from_json"
DB_CHANNEL_ACCOUNT = "account_channel"
DB_CHANNEL_FACILITY = "facility_channel"
DB_CHANNEL_ASSET = "asset_channel"
DB_CHANNEL_SERVICE = "service_channel"
DB_CHANNEL_USER = "user_channel"
DB_CHANNEL_USERFACILITY = "userfacility_channel"
DB_CHANNEL_PARENT_FACILITY = "account_channel"


[development]
# Settings for the development environment
LOG_LEVEL = "debug"
DATABASE_NAME = "us_dev_daas"
DATABASE_HOST = "localhost"
DATABASE_PORT = "5432"
DATABASE_SCHEMA = "daas"
SOLR_URL = "http://localhost:8983/solr"
SOLR_TIMEOUT = "10"
SOLR_MAX_ROW = 1000
PAGINATION_SIZE_DB = "10"
PAGINATION_SIZE_SOLR = "10"
IDX_BUFFER_SIZE_ASSET = "10"
IDX_BUFFER_DURATION_ASSET = "10"

[integration]
# Settings for the development environment
LOG_LEVEL = "debug"
DATABASE_NAME = "us_int_daas"
DATABASE_HOST = "host.docker.internal"
DATABASE_PORT = "5432"
DATABASE_SCHEMA = "daas"
SOLR_URL = "http://host.docker.internal:8983/solr"
SOLR_TIMEOUT = "10"
SOLR_MAX_ROW = 1000
PAGINATION_SIZE_DB = "10"
PAGINATION_SIZE_SOLR = "10"
IDX_BUFFER_SIZE_ASSET = "10"
IDX_BUFFER_DURATION_ASSET = "10"

[production]
# Settings for the production environment
LOG_LEVEL = "info"
DATABASE_NAME = "us_prd_daas"
DATABASE_HOST = "host.docker.internal"
DATABASE_PORT = "5432"
DATABASE_SCHEMA = "daas"
SOLR_URL = "http://host.docker.internal:8983/solr"
SOLR_TIMEOUT = "10"
SOLR_MAX_ROW = 1000
PAGINATION_SIZE_DB = "10"
PAGINATION_SIZE_SOLR = "10"
IDX_BUFFER_SIZE_ASSET = "10"
IDX_BUFFER_DURATION_ASSET = "10"
